-- MySQL Script generated by MySQL Workbench
-- Mon Oct 30 12:06:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pilots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pilots` (
  `pilot_id` INT NOT NULL AUTO_INCREMENT,
  `pilotname` VARCHAR(45) NULL,
  PRIMARY KEY (`pilot_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`races`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`races` (
  `race_id` INT NOT NULL AUTO_INCREMENT,
  `racename` VARCHAR(45) NULL,
  `deadline` TIMESTAMP NULL,
  PRIMARY KEY (`race_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`race_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`race_result` (
  `race_id` INT NOT NULL,
  `positions` VARCHAR(99) NULL,
  INDEX `fk_race_result_races1_idx` (`race_id` ASC),
  PRIMARY KEY (`race_id`),
  CONSTRAINT `fk_race_result_races1`
    FOREIGN KEY (`race_id`)
    REFERENCES `mydb`.`races` (`race_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`forecasts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`forecasts` (
  `forecast_id` INT NOT NULL AUTO_INCREMENT,
  `race_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `forecast` VARCHAR(45) NULL,
  PRIMARY KEY (`forecast_id`),
  INDEX `fk_forecasts_races_idx` (`race_id` ASC),
  INDEX `fk_forecasts_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_forecasts_races`
    FOREIGN KEY (`race_id`)
    REFERENCES `mydb`.`races` (`race_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forecasts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fcast_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fcast_result` (
  `result_id` INT NOT NULL AUTO_INCREMENT,
  `forecast_id` INT NOT NULL COMMENT '\n',
  `result_string` VARCHAR(245) NULL,
  PRIMARY KEY (`result_id`),
  INDEX `fk_fcast_result_forecasts1_idx` (`forecast_id` ASC),
  CONSTRAINT `fk_fcast_result_forecasts1`
    FOREIGN KEY (`forecast_id`)
    REFERENCES `mydb`.`forecasts` (`forecast_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
